server:
 port: 8080 
 servlet:
    context-path: /account-service
  
spring:
 application:
  name: Account-Service
  
 datasource:
  url: jdbc:postgresql://localhost:5432/account-db
  username: postgres
  password: Ayush123@
  driver-class-name: org.postgresql.Driver
  #initialization-mode: always
  #initialize: true
  #schema: classpath:/schema.sql
  #data: classpath:/data.sql
  #continue-on-error: true
  
 jpa:
  show-sql: true
  properties:
   hibernate:
    dialect: org.hibernate.dialect.PostgreSQLDialect
    format_sql: true
  hibernate:
   ddl-auto: update
   
springdoc:
 api-docs:
  path: /account-docs
